### ISSUE TITLE
example error

### ISSUE THREAD

**Issue by ChengYen-Tang** [islamelnabarawy/sc2gym#5]
I get the following error when I run full_game_random.

```
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File ".\full_game_random.py", line 66, in <module>
    main()
  File ".\full_game_random.py", line 48, in main
    obs = env.reset()
  File "e:\code\machinelearning\env\sc2gym\sc2gym\envs\sc2_game.py", line 72, in reset
    self._init_env()
  File "e:\code\machinelearning\env\sc2gym\sc2gym\envs\sc2_game.py", line 92, in _init_env
    self._env = sc2_env.SC2Env(**args)
  File "C:\Users\Kenneth\AppData\Roaming\Python\Python37\site-packages\pysc2\env\sc2_env.py", line 211, in __init__
    raise ValueError("You must specify the list of players.")
ValueError: You must specify the list of players.
```

**Comment by islamelnabarawy** [comment]
Hi @ChengYen-Tang, can you please provide some more information? Which platform, which game client and version, and which version of python are you running?

**Comment by ChengYen-Tang** [comment]
I use windows，SC2 client version is 4.10.4.76811, python version is 3.7

**Comment by islamelnabarawy** [comment]
I don't have access to a Windows machine to fix this right now, and my wine
installation has recently broken as well. I think I will have to rely on
the community to investigate and fix this.

Contributions and pull requests are welcome.
